# **Content based recommendation system**

In [1]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("dataset.csv")
df.head()

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 10000 non-null  int64
 1   title              10000 non-null  object
 2   genre              9997 non-null   object
 3   original_language  10000 non-null  object
 4   overview           9987 non-null   object
 5   popularity         10000 non-null  float64
 6   release_date       10000 non-null  object
 7   vote_average       10000 non-null  float64
 8   vote_count         10000 non-null  int64
dtypes: float64(2), int64(2), object(5)
memory usage: 703.3+ KB

In [4]:
df.describe()

                  id    popularity  vote_average    vote_count
count   10000.000000  10000.000000  10000.000000  10000.000000
mean   161243.505000     34.697267      6.621150   1547.309400
std    211422.046043    211.684175      0.766231   2648.295789
min         5.000000      0.600000      4.600000    200.000000
25%     10127.750000      9.154750      6.100000    315.000000
50%     30002.500000     13.637500      6.600000    583.500000
75%    310133.500000     25.651250      7.200000   1460.000000
max    934761.000000  10436.917000      8.700000  31917.000000

In [5]:
df.columns

Index(['id', 'title', 'genre', 'original_language', 'overview', 'popularity',
       'release_date', 'vote_average', 'vote_count'],
      dtype='object')

## **Feature Selection**

id, title, genre, overview

In [6]:
df = df[["id", "title", "genre", "overview"]]

In [7]:
df.head()

,id,title,genre,overview
0,278,The Shawshank Redemption,"Drama,Crime",Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance","Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Drama,Crime","Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,"Drama,History,War",The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,"Drama,Crime",In the continuing saga of the Corleone crime f...

In [8]:
df["tags"] = df["overview"]+df["genre"]
df.head(1)

,id,title,genre,overview,tags
0,278,The Shawshank Redemption,"Drama,Crime",Framed in the 1940s for the double murder of h...,Framed in the 1940s for the double murder of h...

In [9]:
df.tags

0       Framed in the 1940s for the double murder of h...
1       Raj is a rich, carefree, happy-go-lucky second...
2       Spanning the years 1945 to 1955, a chronicle o...
3       The true story of how businessman Oskar Schind...
4       In the continuing saga of the Corleone crime f...
                              ...
9995    The story follows the adventures of Aang, a yo...
9996    The sharks take bite out of the East Coast whe...
9997    During World War II, a brave, patriotic Americ...
9998    A man named Farmer sets out to rescue his kidn...
9999    Seeking justice for his partner’s murder by an...
Name: tags, Length: 10000, dtype: object

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        10000 non-null  int64
 1   title     10000 non-null  object
 2   genre     9997 non-null   object
 3   overview  9987 non-null   object
 4   tags      9985 non-null   object
dtypes: int64(1), object(4)
memory usage: 390.8+ KB

In [11]:
features = df.drop(columns=["genre", "overview"])
features.head()

,id,title,tags
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...

### **Vectorizing the tags**
NB: CountVectorizer has been imported

In [12]:
cv = CountVectorizer(max_features=10000, stop_words='english')

In [13]:
tags_vector = cv.fit_transform(features["tags"].values.astype("U")).toarray()

In [14]:
tags_vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [15]:
import seaborn as sns

In [ ]:
sns.scatterplot(tags_vector)

In [15]:
tags_vector.ndim

2

### **Cosine Similarities**
Nb: ``cosine_similarity`` has been imported

In [16]:
similarity_cos = cosine_similarity(tags_vector)

In [17]:
similarity_cos

array([[1.        , 0.05634362, 0.13041013, ..., 0.07559289, 0.11065667,
        0.06900656],
       [0.05634362, 1.        , 0.07715167, ..., 0.        , 0.03636965,
        0.        ],
       [0.13041013, 0.07715167, 1.        , ..., 0.02300219, 0.0673435 ,
        0.09449112],
       ...,
       [0.07559289, 0.        , 0.02300219, ..., 1.        , 0.03253   ,
        0.03042903],
       [0.11065667, 0.03636965, 0.0673435 , ..., 0.03253   , 1.        ,
        0.04454354],
       [0.06900656, 0.        , 0.09449112, ..., 0.03042903, 0.04454354,
        1.        ]])

### **Getting films index number**

In [18]:
features[features["title"]=="The Godfather"].index[0]

np.int64(2)

In [19]:
similarity_cos[2]

array([0.13041013, 0.07715167, 1.        , ..., 0.02300219, 0.0673435 ,
       0.09449112])

In [20]:
distance = sorted(list(enumerate(similarity_cos[2])), reverse=True, key=lambda tags_vector:tags_vector[1])
distance[0:5]

[(2, np.float64(1.0000000000000004)),
 (4, np.float64(0.4763305116224667)),
 (7419, np.float64(0.35634832254989923)),
 (153, np.float64(0.33946736991660215)),
 (2624, np.float64(0.32732683535398854))]

In [24]:
for i in distance[0:5]:
    print(features.iloc[i[0]].title)

The Godfather
The Godfather: Part II
Blood Ties
Joker
Bomb City

In [25]:
def recommend(movies):
    try:
        index = features[features["title"]==movies].index[0]
        distance = sorted(list(enumerate(similarity_cos[index])), reverse=True, key=lambda tags_vector:tags_vector[1])
        for i in distance[1:10]:
            print(features.iloc[i[0]].title)
    except:
        print(f'no content on {movies}')

In [27]:
recommend("Thor")

Thor: Love and Thunder
Thor: The Dark World
Thor: Ragnarok
Eternals
Godzilla: The Planet Eater
Wonder Woman
Team Thor: Part 2
Iron Sky: The Coming Race
Supergirl

## **Saving the Model**

In [43]:
import pickle

In [44]:
pickle.dump(features, open("movies_list.pkl", "wb"))
pickle.dump(similarity_cos, open("similarity_cos.pkl", "wb"))

In [45]:
pickle.load(open("movies_list.pkl", "rb"))

,id,title,tags
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...
...,...,...,...
9995,10196,The Last Airbender,"The story follows the adventures of Aang, a yo..."
9996,331446,Sharknado 3: Oh Hell No!,The sharks take bite out of the East Coast whe...
9997,13995,Captain America,"During World War II, a brave, patriotic Americ..."
9998,2312,In the Name of the King: A Dungeon Siege Tale,A man named Farmer sets out to rescue his kidn...
9999,455957,Domino,Seeking justice for his partner’s murder by an...